In [2]:
import pandas as pd 
import re

# Loading in the data
This code takes the csv file from MZmine3 output

In [3]:
df = pd.read_csv(r"C:\Users\adamg\OneDrive - The University of Liverpool\Project Work\MZmine\04JunW2\04JunW2.csv")

Taking a look at the data, it is important to get a feel for what the data looks like

In [4]:
# First 5 rows 
df.head()

,id,area,rt,mz_range:min,mz_range:max,charge,fragment_scans,alignment_scores:rate,alignment_scores:aligned_features_n,alignment_scores:align_extra_features,...,datafile:Combined_P9_t11h.mzML:mz_range:max,datafile:Combined_P9_t11h.mzML:rt_range:min,datafile:Combined_P9_t11h.mzML:rt_range:max,datafile:Combined_P9_t11h.mzML:feature_state,datafile:Combined_P9_t11h.mzML:mz,datafile:Combined_P9_t11h.mzML:intensity_range:min,datafile:Combined_P9_t11h.mzML:intensity_range:max,datafile:Combined_P9_t11h.mzML:height,datafile:Combined_P9_t11h.mzML:charge,datafile:Combined_P9_t11h.mzML:isotopes
0,1,0.0,0.0031,181.02576,181.02576,NaN,0,0.008,1,0,...,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0.0,0.0031,243.18047,243.18047,NaN,0,0.008,1,0,...,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,0.0,0.0031,168.14813,168.14813,NaN,0,0.008,1,33,...,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,0.0,0.0031,119.08731,119.08731,1.0,0,0.008,1,6,...,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0.0,0.0031,120.08813,120.08813,1.0,0,0.008,1,1,...,NaN,NaN,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Shape of the dataframe
df.shape

(981, 1555)

In [6]:
df.columns

Index(['id', 'area', 'rt', 'mz_range:min', 'mz_range:max', 'charge',
       'fragment_scans', 'alignment_scores:rate',
       'alignment_scores:aligned_features_n',
       'alignment_scores:align_extra_features',
       ...
       'datafile:Combined_P9_t11h.mzML:mz_range:max',
       'datafile:Combined_P9_t11h.mzML:rt_range:min',
       'datafile:Combined_P9_t11h.mzML:rt_range:max',
       'datafile:Combined_P9_t11h.mzML:feature_state',
       'datafile:Combined_P9_t11h.mzML:mz',
       'datafile:Combined_P9_t11h.mzML:intensity_range:min',
       'datafile:Combined_P9_t11h.mzML:intensity_range:max',
       'datafile:Combined_P9_t11h.mzML:height',
       'datafile:Combined_P9_t11h.mzML:charge',
       'datafile:Combined_P9_t11h.mzML:isotopes'],
      dtype='object', length=1555)

# Only taking the necessary columns
For now I only need the id and then the columns that contain the intensities

In [40]:
# Getting the intensities 
pattern = r"datafile:Combined_P(\d)_t(\d)h\.mzML:mz$"

filtered_cols = [col for col in df.columns if re.search(pattern, col)]
filtered_df = pd.concat([df[['id']], df[filtered_cols]], axis=1)

In [41]:
# Function to rename the columns to standardise for the PCA 
def rename_matching_columns(df, pattern):
    def replace_func(matchobj):
        return f"P{matchobj.group(1)}_t{matchobj.group(2)}h"  # Use captured groups for renaming

    cols = [col for col in df.columns if re.search(pattern, col)]
    renamed_cols = [re.sub(pattern, replace_func, col) for col in cols]
    return df.rename(columns=dict(zip(cols, renamed_cols)))

filtered_df = rename_matching_columns(filtered_df,pattern)

filtered_df.to_csv("MZmine_Feature_Matrix.csv", index=False)